//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Akademiki
    {
        public int Id_akademiki { get; set; }
        public string Fam { get; set; }
        public string Name { get; set; }
        public string Otchestvo { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Specialisation { get; set; }
        public Nullable<int> Year_zvanie { get; set; }
    }
}
