//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int Id_country { get; set; }
        public string Tittle { get; set; }
        public string Capital { get; set; }
        public Nullable<int> Square { get; set; }
        public Nullable<int> Population { get; set; }
        public string Continent { get; set; }
    }
}
