//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Numder { get; set; }
        public string Shifr { get; set; }
        public string Fam { get; set; }
        public string Dolzhnost { get; set; }
        public Nullable<decimal> Zp { get; set; }
        public Nullable<int> Shef { get; set; }
    
        public virtual Kafedra Kafedra { get; set; }
        public virtual Ingener Ingener { get; set; }
        public virtual Prepod Prepod { get; set; }
        public virtual ZavKafedra ZavKafedra { get; set; }
    }
}
