//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<int> RegNumber { get; set; }
        public Nullable<int> Number { get; set; }
        public string Auditoria { get; set; }
        public Nullable<int> Otsenka { get; set; }
        public int Id_exam { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Prepod Prepod { get; set; }
        public virtual Student Student { get; set; }
    }
}
