//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exam()
        {
            this.ExamResult = new HashSet<ExamResult>();
        }
    
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int id_distcipline { get; set; }
        public int code { get; set; }
        public string ayditory { get; set; }
        public int id_employe { get; set; }
        public int id_group { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Employe Employe { get; set; }
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamResult> ExamResult { get; set; }
    }
}
