//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gimnazisty
    {
        public int ID { get; set; }
        public string Fam { get; set; }
        public string Predmet { get; set; }
        public string School { get; set; }
        public Nullable<double> Ball { get; set; }
    }
}
