//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UchPr_Basharova_321Entities : DbContext
    {
        public UchPr_Basharova_321Entities()
            : base("name=UchPr_Basharova_321Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Akademiki> Akademiki { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Country_Basharova> Country_Basharova { get; set; }
        public virtual DbSet<Discipline> Discipline { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Exam> Exam { get; set; }
        public virtual DbSet<Fakultet> Fakultet { get; set; }
        public virtual DbSet<Kafedra> Kafedra { get; set; }
        public virtual DbSet<Prepod> Prepod { get; set; }
        public virtual DbSet<Specialnost> Specialnost { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Uchenik> Uchenik { get; set; }
        public virtual DbSet<Upravlenie_Basharova> Upravlenie_Basharova { get; set; }
        public virtual DbSet<Zayavka> Zayavka { get; set; }
        public virtual DbSet<Animal_Basharova> Animal_Basharova { get; set; }
        public virtual DbSet<Flower_Basharova> Flower_Basharova { get; set; }
        public virtual DbSet<Gimnazisty> Gimnazisty { get; set; }
        public virtual DbSet<Ingener> Ingener { get; set; }
        public virtual DbSet<ZavKafedra> ZavKafedra { get; set; }
    }
}
