//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zayavka
    {
        public Nullable<int> Code { get; set; }
        public string Numder { get; set; }
        public int Id_zayavka { get; set; }
    
        public virtual Specialnost Specialnost { get; set; }
    }
}
